services:
  backend:
    build: ./backend
    ports:
      - 8001:8001
    environment:
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=DB_vagas
      - DB_HOST=db
      - JWT_SECRET=3271cn203nd83921ncd7sc7et2a

    volumes:
      - ./backend:/Application
    
    container_name: vagasAPI
    restart: always
    depends_on:
      - db



  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      
    restart: always